### ISSUE TITLE
Add examples for frequency table and symbols

### ISSUE THREAD

**Issue by Mitiko** [Mitiko/CompressionPipeline#6]
Best way to show this is with a huffman example.  

### TODO:
 - [ ] Add documentation on github, do not overuse the examples section
 - [ ] Add link form the README to the docs
 - [ ] Mention how to create other generic data (genes use 2 bits, not 1 byte)
 - [ ] Mention PPM and Markov and CM can create its own frequency table
